[package]
name = "xcb-util-cursor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "xcb_util_cursor"
path = "lib.rs"

[dependencies]
xcb = "1.2.0"
anyhow = "1.0.66"

[dependencies.xcb-util-cursor-sys]
version = "0.1.0"
path = "xcb-util-cursor-sys"
